### ISSUE TITLE
only one label is being rendered

### ISSUE THREAD

**Issue by alexbodn** [jhuckaby/pixl-chart#1]
hello friend and a big thank for providing pixl-chart.
it allowed me to build a modest chart to check some complex info.
will gladly share my program.
however, there is a small issue: 
disregarding the number of labels in my data points, only the first one 
gets rendered, however renderDataLabels loops over all of them.
i'll be glad to further test.

thanks,
alex

**Comment by alexbodn** [comment]
[labeled-chart.zip](https://github.com/jhuckaby/pixl-chart/files/9804139/labeled-chart.zip)

please see the data in the orders layers, from line 28694 in my html.
you may use my file for any purpose you wish.

**Comment by jhuckaby** [comment]
Thanks so much for this issue report.  It's all fixed in v1.0.2, which was just pushed.
